### ISSUE TITLE
Get rid of local deliver

### ISSUE THREAD

**Issue by lakruzz** [devx-cafe/git-phlow#78]
The robot version implement in #53 should _replace `git phlow deliver --local` we don't need both.

Let's get rid of the syntactical sugar and remove the `deliver --local` feature

**Comment by lakruzz** [comment]
Related to @bicschneider [commen on slack](https://praqma.slack.com/archives/C3MEY9LF2/p1490184760122177)

**Comment by groenborg** [comment]
@lakruzz in relation to our meeting, I think we agreed on keeping the feature, and then we will have a meeting where we can lock on a better terminology. I have renamed the issue because of this.

**Comment by lakruzz** [comment]
@groenborg that's a different case, not the same case with a new name.

And regarding the terminology, It side tracking, too many people who are involved but not commited, are having free opinions basend on thought experiments and guessed end user behaviour -and they all differ. 

We are not going to vote about this (if we are, then only end-users, not chickens, will be eligible to vote)

We will put it to rest

**Comment by groenborg** [comment]
@lakruzz I think we still should remove the local deliver and use the agent subcommand in stead, are we in agreement?
